[package]
name = "tsiang"
version = "0.1.0"
authors = ["karnpapon <karnpapon@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tui = "0.5"
termion = "1.5"
failure = "0.1"
ignore = "0.4"
shells = "0.2.0"
